openapi: 3.0.3
info:
  title: Api betvictor
  description: Api betvictor
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/api/betvictor'
tags:
  - name: text
    description: Process text data
components:
  schemas:
    Empty:
      type: object
      description: Empty object
      properties:
        code:
          type: string
paths:
  /text:
    get:
      tags:
        - text
      description: Returns information about text retrieved and processed
      operationId: getRetrievedTextInfo
      parameters:
        - in: query
          name: paragraphNumber
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: Text information response
          content:
            application/json:
              schema:
                $ref: 'RetrievedTextInfoResponse'
        '401':
          description: UNAUTHORIZED
          content:
            application/json:
              schema:
                $ref: 'ApiError'
        '404':
          description: NOT_FOUND
          content:
            application/json:
              schema:
                $ref: 'ApiError'
        '500':
          description: INTERNAL_SERVER_ERROR
          content:
            application/json:
              schema:
                $ref: 'ApiError'