spring:
  kafka:
#    bootstrap-servers: localhost:9092
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false
      auto:
        create:
          topics:
            enable=true

#spring:
#  kafka:
#    #bootstrap-servers: localhost:9092
#    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
##    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    properties:
#      spring.json.add.type.headers: false
#      auto:
#        create:
#          topics:
#            enable=true:
#
#  jackson:
#    serialization:
#      INDENT_OUTPUT: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, info, prometheus, logfile, flyway
#  endpoint:
#    health:
#      show-details: always
#
